FROM python:3.11-slim

# Устанавливаем системные зависимости: tshark и средства компиляции
RUN apt update && apt install -y \
    tshark \
    net-tools \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Копируем requirements и устанавливаем зависимости
COPY requirements-sniffer.txt .
RUN pip install --no-cache-dir -r requirements-sniffer.txt

# Копируем сам скрипт
COPY traffic_sniffer.py .

CMD ["python", "-u", "traffic_sniffer.py"]
